[package]
name = "redis-pool"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
redis-module = {version = "0.24.0", features = ["experimental-api"]}
chrono = "0.4.19"


[dev-dependencies]
anyhow = "1.0.38"
redis = "0.21.0"